### ISSUE TITLE
Add simple logging of basic labeling information

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/cell_labeling_app#31]
It is probably going to be valuable to have recorded some basic information about what the users are labeling.  This issue is to add some very basic logging to the cell labeling app. 

Information to include:
* experiment id
* Region id

Tasks:
- [ ] Determine what information should be logged
- [ ] Implement logging

Validation:
log file of information recorded from app

**Comment by aamster** [comment]
![Screen Shot 2022-03-11 at 12.41.41 PM.png](https://images.zenhubusercontent.com/5fa1b163d87c6f82dfbeed1a/d6a420f2-ba83-4c51-b058-c664762a7eb1)
