### ISSUE TITLE
Labeling effort demo and support

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/cell_labeling_app#32]
During the labeling effort, we expect to spend some time orienting the users with the task and the tool, answering user questions, addressing issues that arise.

Demo to users: March 6th-ish

Validation:
Successful labeling effort that results in data needed to do accurate classification.

**Comment by morriscb** [comment]
Gonna add this here. Created a slide deck as a reference for users of the labeling app/for use when presenting the demo.

[Slides](https://alleninstitute-my.sharepoint.com/:p:/g/personal/chris_morrison_alleninstitute_org/EQp2bfkCu49Nrz21JMvHJaYBBo_P8P1ZceGBr2N4_k2R6A?e=P9infx)

**Comment by morriscb** [comment]
Created short set of slides to propose a train/test split for labeling effort: https://alleninstitute-my.sharepoint.com/:p:/g/personal/chris_morrison_alleninstitute_org/EedYw3ceAe1Ih3l8CqB03O8BNPPyplqUkZqGywzVLiwoaw?e=AeyrX8
